<?php

/**
 * @file
 * Contains reacttest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function reacttest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the reacttest module.
    case 'help.page.reacttest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My awesome react module') . '</p>';
      return $output;

    default:
  }
}
